# Generated by Django 2.2.9 on 2020-02-15 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=2000)),
                ('salle', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('selectionner', models.BooleanField(default=True)),
                ('chef', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('niveau', models.CharField(choices=[('Niveau 1', 'Niveau 1'), ('Niveau 2', 'Niveau 2'), ('Niveau 3', 'Niveau 3')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=8)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='participant.Equipe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
