# Generated by Django 2.2.1 on 2020-02-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='niveau',
            field=models.CharField(choices=[('Niveau 1', 'Licence 1'), ('Niveau 2', 'Licence 2 - Licence 3'), ('Niveau 3', 'Master 1')], max_length=8),
        ),
    ]
