# Generated by Django 3.0.3 on 2020-02-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_auto_20200214_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='salle',
            field=models.CharField(blank=True, choices=[], default='', max_length=20, null=True),
        ),
    ]
