# Generated by Django 3.0.3 on 2020-02-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_auto_20200215_0010'),
        ('participant', '0002_auto_20200215_0348'),
    ]

    operations = [
    ]
