# Generated by Django 3.0.3 on 2020-02-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_merge_20200215_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='numero',
        ),
    ]
