# Generated by Django 3.0.3 on 2020-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0006_remove_participant_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='numero',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
