# Generated by Django 3.0.3 on 2020-02-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0007_participant_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_chief',
            field=models.BooleanField(default=False),
        ),
    ]
