# Generated by Django 3.0.3 on 2020-02-27 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participant', '0008_participant_is_chief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de restauration')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='participant.Participant')),
            ],
        ),
    ]
