# Generated by Django 3.0.3 on 2020-02-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatConstante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mx_plat', models.IntegerField(default=6, verbose_name='Nombre de plats maximal')),
                ('mx_plat_matin', models.IntegerField(default=2, verbose_name='Nom de plats maximal du main')),
                ('mx_plat_midi', models.IntegerField(default=2, verbose_name='Nom de plats maximal du soir')),
            ],
        ),
    ]
