# Generated by Django 3.0.3 on 2020-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_platconstante'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='jour',
            field=models.CharField(choices=[('vendredi', 'vendredi'), ('samedi', 'samedi'), ('dimanche', 'dimanche')], default='vendredi', max_length=100),
        ),
        migrations.AddField(
            model_name='plat',
            name='periode',
            field=models.CharField(choices=[('matin', 'matin'), ('midi', 'midi'), ('soir', 'soir')], default='soir', max_length=100),
        ),
        migrations.AddField(
            model_name='plat',
            name='type',
            field=models.CharField(choices=[('repas', 'repas'), ('boisson', 'boisson'), ('autre', 'autre')], default='repas', max_length=100),
        ),
    ]
