# Generated by Django 3.0.3 on 2020-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=8)),
                ('sujet', models.CharField(choices=[("Retour d'information", 0), ('Rapport de bug', 1), ('Demande de fonctionnalité', 2)], max_length=150)),
                ('contenu', models.TextField(null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
            ],
        ),
    ]
