# Generated by Django 3.0.3 on 2020-02-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technohack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='traiter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billet',
            name='sujet',
            field=models.CharField(choices=[('0', "Retour d'information"), ('1', 'Rapport de bug'), ('2', 'Demande de fonctionnalité')], max_length=150),
        ),
    ]
